markets:
  - geo_id: dc_city
    level: city
    match:
      - "washington, dc"
      - "washington dc"
      - "washington"
      - "dc"

  - geo_id: dc_state
    level: state
    match:
      - "district of columbia"
      - "washington dc"
      - "dc"

  - geo_id: dc_county
    level: county
    match:
      - "district of columbia county, dc"
      - "district of columbia county"
      - "district of columbia"
      - "washington, dc"
